language: java
jdk: oraclejdk8

dist: trusty

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: reports
  target_branch: gh-pages
  keep_history: false
  on:
    branch: gh-pages
