language: java
install: true
jdk: oraclejdk8

script:
  - ./gradlew build --scan -s

before_cache:
  - rm -f $HOME/.gradle/chaches/modules-2/modules-2.lock
  - rm -fr $HOME//gradle/chaches/*/plugin-resolution/
  
cache:
  directiories:
    - $HOME/.gradle/caches
    - $Home/.gralde/wrapper/
